name: Run Front-End Unit Tests

on: workflow_dispatch

jobs:
  RunUnitTests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Run Unit Tests
        run: npm test
