name: Sync Fork

on:
  repository_dispatch:
    types: [sync]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: Fabeure/Studyfied
          target_repository: Saber-Azouzi/Studyfied
          upstream_branch: dev
          target_branch: dev
          force: true
          tags: true